In [ ]:
import numpy as np
from numpy.linalg import qr

In [ ]:
a = np.array([[1.5, 1, 0], 
              [1, 2, 1],
              [0, 1, 3]])
for i in range(20):
    q, r = qr(a)
    a = np.dot(r, q)
    print(f'Iteration {i+1}:')
    print('A', a)

Iteration 1:
A [[ 2.57692308e+00  8.28486893e-01 -3.74470199e-17]
 [ 8.28486893e-01  2.68169761e+00 -1.11896419e+00]
 [ 0.00000000e+00 -1.11896419e+00  1.24137931e+00]]
Iteration 2:
A [[ 3.06955381e+00  7.82698113e-01 -5.91798777e-17]
 [ 7.82698113e-01  2.84588340e+00  2.84465082e-01]
 [ 0.00000000e+00  2.84465082e-01  5.84562792e-01]]
Iteration 3:
A [[ 3.43068724e+00  6.37467058e-01  2.18136554e-16]
 [ 6.37467058e-01  2.52206333e+00 -6.07089855e-02]
 [ 0.00000000e+00 -6.07089855e-02  5.47249426e-01]]
Iteration 4:
A [[ 3.62935587e+00  4.31859897e-01 -3.10883291e-16]
 [ 4.31859897e-01  2.32528797e+00  1.40100403e-02]
 [ 0.00000000e+00  1.40100403e-02  5.45356162e-01]]
Iteration 5:
A [[ 3.71248944e+00  2.66800843e-01  3.66726958e-16]
 [ 2.66800843e-01  2.24226171e+00 -3.38310631e-03]
 [ 0.00000000e+00 -3.38310631e-03  5.45248852e-01]]
Iteration 6:
A [[ 3.74308584e+00  1.58943174e-01 -3.98266612e-16]
 [ 1.58943174e-01  2.21167172e+00  8.31892630e-04]
 [ 0.00000000e+00  8.31892630e-04  5.4

In [ ]:
print(2.4412*(0.36761))

0.897409532


In [ ]:
p = [1, 5, 10, 20]
for i in range(20):
    q, r = qr(b)
    b = np.dot(r, q)
    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(b)

Iteration 1:
[[ 3.00000055e+00 -3.06635431e-06]
 [-3.06635431e-06  1.58578644e+00]]
Iteration 5:
[[ 3.00000055e+00 -2.39395396e-07]
 [-2.39395396e-07  1.58578644e+00]]
Iteration 10:
[[3.00000055e+00 9.87944686e-09]
 [9.87944656e-09 1.58578644e+00]]
Iteration 20:
[[3.00000055e+00 1.68257333e-11]
 [1.68254335e-11 1.58578644e+00]]


In [ ]:
from math import sqrt
print(2.7802140 + 2+ (1-sqrt(3))/2)

4.414188596215562
