In [ ]:
#import module yang dibutuhkan
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [ ]:
#upload file
from google.colab import files
upload = files.upload()

Saving CreditCard.csv to CreditCard.csv


In [ ]:
#cek data
credit_df = pd.read_csv("CreditCard.csv")
credit_df.head()

ID  Gender  Own_car  Own_property  Work_phone  Phone  Email  \
0  5008804       1        1             1           1      0      0   
1  5008806       1        1             1           0      0      0   
2  5008808       0        0             1           0      1      1   
3  5008812       0        0             1           0      0      0   
4  5008815       1        1             1           1      1      1   

   Unemployed  Num_children  Num_family  Account_length  Total_income  \
0           0             0           2              15      427500.0   
1           0             0           2              29      112500.0   
2           0             0           1               4      270000.0   
3           1             0           1              20      283500.0   
4           0             0           2               5      270000.0   

         Age  Years_employed           Income_type  \
0  32.868574       12.435574               Working   
1  58.793815        3.104787               Working   
2  52.321403        8.353354  Commercial associate   
3  61.504343        0.000000             Pensioner   
4  46.193967        2.105450               Working   

                  Education_type         Family_status       Housing_type  \
0               Higher education        Civil marriage   Rented apartment   
1  Secondary / secondary special               Married  House / apartment   
2  Secondary / secondary special  Single / not married  House / apartment   
3               Higher education             Separated  House / apartment   
4               Higher education               Married  House / apartment   

  Occupation_type  Target  
0           Other       1  
1  Security staff       0  
2     Sales staff       0  
3           Other       0  
4     Accountants       0

In [ ]:
#cek banyak data
credit_df.shape

(9709, 20)

In [ ]:
#cek data apa saja pada Education_type
credit_df["Education_type"].unique()

array(['Higher education', 'Secondary / secondary special',
       'Incomplete higher', 'Lower secondary', 'Academic degree'],
      dtype=object)

In [ ]:
#Pilih atribut yang kemungkinan besar berpengaruh pada risiko gagal bayar atau tidak 
credit_df = credit_df[['Own_property', 'Total_income', 'Age', 'Years_employed','Education_type','Target']]
credit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9709 entries, 0 to 9708
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Own_property    9709 non-null   int64  
 1   Total_income    9709 non-null   float64
 2   Age             9709 non-null   float64
 3   Years_employed  9709 non-null   float64
 4   Education_type  9709 non-null   object 
 5   Target          9709 non-null   int64  
dtypes: float64(3), int64(2), object(1)
memory usage: 455.2+ KB


In [ ]:
#ubah data ke integer
credit_df['Total_income'] = credit_df['Total_income'].astype('int')
credit_df['Age'] = credit_df['Age'].astype('int')
credit_df['Years_employed'] = credit_df['Years_employed'].astype('int')
credit_df.head()
credit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9709 entries, 0 to 9708
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Own_property    9709 non-null   int64 
 1   Total_income    9709 non-null   int64 
 2   Age             9709 non-null   int64 
 3   Years_employed  9709 non-null   int64 
 4   Education_type  9709 non-null   object
 5   Target          9709 non-null   int64 
dtypes: int64(5), object(1)
memory usage: 455.2+ KB


In [ ]:
#Definisikan X
X = credit_df[['Own_property', 'Total_income', 'Age','Years_employed','Education_type']].values
X[0:5]

array([[1, 427500, 32, 12, 'Higher education'],
       [1, 112500, 58, 3, 'Secondary / secondary special'],
       [1, 270000, 52, 8, 'Secondary / secondary special'],
       [1, 283500, 61, 0, 'Higher education'],
       [1, 270000, 46, 2, 'Higher education']], dtype=object)

In [ ]:
#ubah data pada atribut Education_type ke numerik
from sklearn import preprocessing
le_edu = preprocessing.LabelEncoder()
le_edu.fit(['Academic degree','Higher education','Incomplete higher', 'Secondary / secondary special','Lower secondary'])
X[:, 4] = le_edu.transform(X[:, 4])
X[0:5]

array([[1, 427500, 32, 12, 1],
       [1, 112500, 58, 3, 4],
       [1, 270000, 52, 8, 4],
       [1, 283500, 61, 0, 1],
       [1, 270000, 46, 2, 1]], dtype=object)

In [ ]:
#Definisikan y
y = credit_df['Target']
y[0:5]


0    1
1    0
2    0
3    0
4    0
Name: Target, dtype: int64

In [ ]:
#Definisikan data train dan test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [ ]:
print(X_train.shape)
print(y_train.shape)

(7767, 5)
(7767,)


In [ ]:
print(X_test.shape)
print(y_test.shape)

(1942, 5)
(1942,)


In [ ]:
Targettree = DecisionTreeClassifier(criterion = 'entropy', max_depth = 4)

In [ ]:
Targettree.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [ ]:
predTree = Targettree.predict(X_test)
predTree

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
comparison = {"y_test" : y_test,
 "Predicted": predTree}
comp = pd.DataFrame(comparison)
comp

y_test  Predicted
2141       0          0
2787       0          0
3586       0          0
7190       0          0
277        0          0
...      ...        ...
5219       0          1
4647       0          0
140        0          0
7123       0          0
8804       0          0

[1942 rows x 2 columns]

In [ ]:
from sklearn.metrics import accuracy_score
print("Accuracy : ", accuracy_score(y_test, predTree) )

Accuracy :  0.8614830072090628


In [ ]:
!conda install -c conda-forge pydotplus -y
!conda install -c conda-forge python-graphviz -y

/bin/bash: conda: command not found
/bin/bash: conda: command not found


In [ ]:
from io import StringIO
import pydotplus
import matplotlib.image as mpimg
from sklearn import tree
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train,y_train)

SVC()

In [ ]:
yhat = clf.predict(X_test)
yhat[0:5]

array([0, 0, 0, 0, 0])

In [ ]:
#Buat gambar Decision Tree
dot_data = StringIO()
filename = 'Targettree.png'
featureNames = X[0:5]
out = tree.export_graphviz(Targettree, feature_names = featureNames, out_file = dot_data, class_names = np.unique(y_train), 
                           filled=True, special_characters = True, rotate = False)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_png(filename)
img = mpimg.imread(filename)
plt.figure(figsize = (100, 200))
plt.imshow(img, interpolation='nearest')

TypeError: ignored

Algoritma/Ide:
1. Import module yang dibutuhkan
2. Upload data dan cek data
3. Definisikan X dan y
4. Definisikan Data Train dan test
5. Buat Decision Tree untuk memprediksi apa sebab-sebab risiko gagal bayar berdasarkan atribut yang kita pilih.