In [ ]:
import numpy as np
from random import randint

a11 = randint(-99,99)
a12 = randint(-99,99)
a13 = randint(-99,99)
a14 = randint(-99,99)
a15 = randint(-99,99)
a21 = randint(-99,99)
a22 = randint(-99,99)
a23 = randint(-99,99)
a24 = randint(-99,99)
a25 = randint(-99,99)
a31 = randint(-99,99)
a32 = randint(-99,99)
a33 = randint(-99,99)
a34 = randint(-99,99)
a35 = randint(-99,99)
a41 = 6
a42 = 8
a43 = 8
a44 = 4
a45 = 0
#untuk input entri-entri matriks A

#matriks A dibagi menjadi 2 matriks, yaitu a dan b sebagai berikut.
a = np.array([[a11 , a12, a13, a14], [a21, a22, a23, a24], [a31, a32, a33, a34], [a41, a42, a43, a44]])
b = np.array([a15, a25, a35, a45])
n = len(b)

def swapRows(v,i,j): #definisi pertukaran/pergantian baris
  if len(v.shape) == 1:
    v[i],v[j] = v[j],v[i]
  else:
    v[[i,j],:] = v[[j,i],:]
def gaussPivot(a,b,tol=1.0e-12): #definisi gauss pivoting
  n = len(b)
  s = np.zeros(n)
  for i in range(n):
    s[i] = max(np.abs(a[i,:]))

print("a:", a)
print("-----")
print("b:", b)
print("-----")
print("s:", s)
print("-----")
for k in range(0,n-1):
  
  p = np.argmax(np.abs(a[k:n,k])/s[k:n]) + k #sebuah variabel untuk menentukan baris mana yang posisinya harus bergantian

  print("p :", p)
  print("k :", p)

  if p != k:
      swapRows(b,k,p)
      swapRows(s,k,p)
      swapRows(a,k,p)
  print("a:", a)
  print("-----")
  print("b:", b)
  print("-----")
  print("s:", s)
  print("----eliminasi----")
 #langkah-langkah eliminasi untuk mencari solusi
  for i in range(k+1,n):
      if a[i,k] != 0:
        lam = a[i,k]/a[k,k]
        a[i,k+1:n] = a[i,k+1:n] - lam*a[k,k+1:n]
        b[i] = b[i] - lam*b[k]

  print("a:", a)
  print("-----")
  print("b:", b)
  print("-----")
  print("s:", s)
  print("-----")

b[n-1] = b[n-1]/a[n-1,n-1]
for k in range(n-2,-1,-1):
    b[k] = (b[k] - np.dot(a[k,k+1:n],b[k+1:n]))/a[k,k]
    print("b:", b)
    print("Solusi :")
b #solusi akhir

a: [[ -9 -17  44 -33]
 [-53 -24  66 -93]
 [-20 -22  -7  74]
 [  6   8   8   4]]
-----
b: [ 81 -29  63   0]
-----
s: [ 6. 13. 18. 12.]
-----
p : 1
k : 1
a: [[-53 -24  66 -93]
 [ -9 -17  44 -33]
 [-20 -22  -7  74]
 [  6   8   8   4]]
-----
b: [-29  81  63   0]
-----
s: [13.  6. 18. 12.]
----eliminasi----
a: [[-53 -24  66 -93]
 [ -9 -12  32 -17]
 [-20 -12 -31 109]
 [  6   5  15  -6]]
-----
b: [-29  85  73  -3]
-----
s: [13.  6. 18. 12.]
-----
p : 1
k : 1
a: [[-53 -24  66 -93]
 [ -9 -12  32 -17]
 [-20 -12 -31 109]
 [  6   5  15  -6]]
-----
b: [-29  85  73  -3]
-----
s: [13.  6. 18. 12.]
----eliminasi----
a: [[-53 -24  66 -93]
 [ -9 -12  32 -17]
 [-20 -12 -63 126]
 [  6   5  28 -13]]
-----
b: [-29  85 -12  32]
-----
s: [13.  6. 18. 12.]
-----
p : 2
k : 2
a: [[-53 -24  66 -93]
 [ -9 -12  32 -17]
 [-20 -12 -63 126]
 [  6   5  28 -13]]
-----
b: [-29  85 -12  32]
-----
s: [13.  6. 18. 12.]
----eliminasi----
a: [[-53 -24  66 -93]
 [ -9 -12  32 -17]
 [-20 -12 -63 126]
 [  6   5  28  43]]
-----
b:

array([ 3, -7,  0,  0])

Algoritma :
1. import module yang dibutuhkan
2. menentukan atau menginput entri-entri dari matriks
3. pada matriks A dibagi dua bagian, matriks a dan b. dimana, b ini adalah solusi dari matriks a, atau entri matriks A pada a[:, 4]
4. definisikan fungsi swap rows atau pergantian posisi baris pada matriks
5. definisikan fungsi gauss pivoting
6. menentukan variabel p = np.argmax(np.abs(a[k:n,k])/s[k:n]) + k untuk k dari 0 hingga n-1 = 3
7. Jika p tersebut tidak sama dengan k, maka lakukan pergantian baris yang telah disebutkan pada point 4.
8. Lakukan eliminasi
9. Mendapatkan solusi.
